version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      npm-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      npm-production-minor-patch:
        applies-to: "version-updates"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "nostalgist"
      npm-development-minor-patch:
        applies-to: "version-updates"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
      actions-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
